### ISSUE TITLE
Icon does not appear in toolbar

### ISSUE THREAD

**Issue by Mis0u** [AlfonsoML/nbsp#3]
I've installed the plugin, I have no error but the button does not appear in the toolbar. I'm using Symfony 5.2 and EasyAdmin 3

Yaml config :
```yaml
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    default_config: config
    configs:
        config:
            allowedContent: true
            removePlugins: 'elementspath,exportpdf,image,media, about'
        plugins:
            nbsp:
                path: 'ckeditor/plugins/nbsp/'
                filename: 'plugin.js'
```

Controller : 

```php
TextEditorField::new('subtitle', 'subtitle')
                ->setColumns(6)
                ->setFormType(CKEditorType::class)
                ->setFormTypeOptions([
                    'config' => ['toolbar' => [ [ "Source"], [ "insertNbsp" ] ]]
                ])
````
